[package]
name = "peanut"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
axum = "0.6.20"
sqlite = "0.31.1"
tera = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
chrono = "0.4.30"
